package com.example.root.realheart;

import android.content.Context;
import android.content.SharedPreferences;
import android.net.Uri;
import android.os.Bundle;
import android.support.annotation.Nullable;
import android.support.v4.app.Fragment;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.AutoCompleteTextView;
import android.widget.Button;
import android.widget.EditText;

/*
TeamId: Nill
Author List: Amit Vhatkar, Suraj Singh, Akshat Garg
FileName: EmergencyContactFrag.java
Functions: android standard functions
Global Variables:UI related variables, SharedPrefrence Variable

This fragment used to save 3 emergency contacts

the whole amount of commenting is done in OnViewCreated as the all the other functions are generated by android and our main code
is in this function.
 */
public class EmergencyContactFrag extends Fragment {
    // TODO: Rename parameter arguments, choose names that match
    // the fragment initialization parameters, e.g. ARG_ITEM_NUMBER
    private static final String ARG_PARAM1 = "param1";
    private static final String ARG_PARAM2 = "param2";

    // TODO: Rename and change types of parameters
    private String mParam1;
    private String mParam2;

    private OnFragmentInteractionListener mListener;
    AutoCompleteTextView b1,b2,b3;
    Button save,edit;
    SharedPreferences sp;
    SharedPreferences.Editor editor;
    public EmergencyContactFrag() {
        // Required empty public constructor
    }

    /**
     * Use this factory method to create a new instance of
     * this fragment using the provided parameters.
     *
     * @param param1 Parameter 1.
     * @param param2 Parameter 2.
     * @return A new instance of fragment EmergencyContactFrag.
     */
    // TODO: Rename and change types and number of parameters
    public static EmergencyContactFrag newInstance(String param1, String param2) {
        EmergencyContactFrag fragment = new EmergencyContactFrag();
        Bundle args = new Bundle();
        args.putString(ARG_PARAM1, param1);
        args.putString(ARG_PARAM2, param2);
        fragment.setArguments(args);
        return fragment;
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        if (getArguments() != null) {
            mParam1 = getArguments().getString(ARG_PARAM1);
            mParam2 = getArguments().getString(ARG_PARAM2);
        }
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        return inflater.inflate(R.layout.fragment_emergency_contact, container, false);
    }

    // TODO: Rename method, update argument and hook method into UI event
    public void onButtonPressed(Uri uri) {
        if (mListener != null) {
            mListener.onFragmentInteraction(uri);
        }
    }

    @Override
    public void onAttach(Context context) {
        super.onAttach(context);
        if (context instanceof OnFragmentInteractionListener) {
            mListener = (OnFragmentInteractionListener) context;
        } else {
            throw new RuntimeException(context.toString()
                    + " must implement OnFragmentInteractionListener");
        }
    }

    @Override
    public void onDetach() {
        super.onDetach();
        mListener = null;
    }

    /**
     * This interface must be implemented by activities that contain this
     * fragment to allow an interaction in this fragment to be communicated
     * to the activity and potentially other fragments contained in that
     * activity.
     * <p>
     * See the Android Training lesson <a href=
     * "http://developer.android.com/training/basics/fragments/communicating.html"
     * >Communicating with Other Fragments</a> for more information.
     */
    public interface OnFragmentInteractionListener {
        // TODO: Update argument type and name
        void onFragmentInteraction(Uri uri);
    }

    @Override
    public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        //getting UI variable from layout and storing it into our defined global variables
        b1 = (AutoCompleteTextView) view.findViewById(R.id.editText1); // for 1st textview to store number
        b2 = (AutoCompleteTextView) view.findViewById(R.id.editText2); // for 2nd textview to store number
        b3 = (AutoCompleteTextView) view.findViewById(R.id.editText3); // for 3rd textview to store number
        b1.setEnabled(false);
        b2.setEnabled(false);
        b3.setEnabled(false);
        save=(Button)view.findViewById(R.id.save);  //getting save button variables
        save.setOnClickListener(new View.OnClickListener() {

            @Override
            public void onClick(View v) {  // setting OnCLickListener for save button
                // TODO Auto-generated method stub
                String num1=b1.getText().toString();  //getting first number from textview
                String num2=b2.getText().toString();  //getting second number from textview
                String num3=b3.getText().toString();  //getting third number from textview
                if(!num1.equals("") && !num2.equals("") && !num3.equals(""))
                {
                    editor=sp.edit();  //getting editor from shared prefrences to save phone numbers
                    editor.putString("num1", num1);  // saving first number
                    editor.putString("num2", num2);  // saving second number
                    editor.putString("num3", num3);  //saving third number
                    editor.commit();  //committing changes
                }
            }
        });
        edit=(Button)view.findViewById(R.id.edit);  //getting editor object
        edit.setOnClickListener(new View.OnClickListener() {

            @Override
            public void onClick(View v) {  // setting setOnCLickListener for edit button
                // TODO Auto-generated method stub
                b1.setEnabled(true);  // enables first textview
                b2.setEnabled(true);  // enables second textview
                b3.setEnabled(true);  // enables third textview
            }
        });
        sp = getActivity().getSharedPreferences("emer", Context.MODE_PRIVATE); // getting shared prefrence variable to show the previous saved number
        if(sp!=null)
        {
            String num1=sp.getString("num1", null);  //getting first number
            String num2=sp.getString("num2", null);  //getting second number
            String num3=sp.getString("num3", null);  //getting third number
            if(num1!=null && num2!=null && num3!=null )
            {
                b1.setText(num1); //setting first number text
                b2.setText(num2); //setting second number text
                b3.setText(num3); //setting third number text
            }
            else
            {
                b1.setEnabled(true); //setting first textView enabled
                b2.setEnabled(true); //setting second textView enabled
                b3.setEnabled(true); //setting third textView enabled
            }
        }
    }
}
